# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cppTAfact <- function(mDtSEXP, mTtinitSEXP, mAinitSEXP, lambda = 0.0, itersMax = 1000L, tol = 1e-8, tolA = 1e-7, tolT = 1e-7) {
    .Call('MeDeCom_cppTAfact', PACKAGE = 'MeDeCom', mDtSEXP, mTtinitSEXP, mAinitSEXP, lambda, itersMax, tol, tolA, tolT)
}

RHLasso <- function(Ginp, Winp, Ainp, l) {
    .Call('MeDeCom_RHLasso', PACKAGE = 'MeDeCom', Ginp, Winp, Ainp, l)
}

mean_p <- function(x) {
    .Call('MeDeCom_mean_p', PACKAGE = 'MeDeCom', x)
}

mean_s <- function(x) {
    .Call('MeDeCom_mean_s', PACKAGE = 'MeDeCom', x)
}

RQuadHC <- function(Ginp, Winp, Ainp, otol, lconstr, uconstr) {
    .Call('MeDeCom_RQuadHC', PACKAGE = 'MeDeCom', Ginp, Winp, Ainp, otol, lconstr, uconstr)
}

RProjSplxBox <- function(Xinp, linp, uinp) {
    .Call('MeDeCom_RProjSplxBox', PACKAGE = 'MeDeCom', Xinp, linp, uinp)
}

RQuadSimplex <- function(Ginp, Winp, Ainp, ot) {
    .Call('MeDeCom_RQuadSimplex', PACKAGE = 'MeDeCom', Ginp, Winp, Ainp, ot)
}

RQuadSimplexBox <- function(Ginp, Winp, Ainp, linp, uinp, ot) {
    .Call('MeDeCom_RQuadSimplexBox', PACKAGE = 'MeDeCom', Ginp, Winp, Ainp, linp, uinp, ot)
}

