# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RHLasso <- function(Ginp, Winp, Ainp, l) {
    .Call('MeDeCom_RHLasso', PACKAGE = 'MeDeCom', Ginp, Winp, Ainp, l)
}

matMult <- function(Ainp, Binp) {
    .Call('MeDeCom_matMult', PACKAGE = 'MeDeCom', Ainp, Binp)
}

RQuadHC <- function(Ginp, Winp, Ainp, otol, lconstr, uconstr) {
    .Call('MeDeCom_RQuadHC', PACKAGE = 'MeDeCom', Ginp, Winp, Ainp, otol, lconstr, uconstr)
}

RProjSplxBox <- function(Xinp, linp, uinp) {
    .Call('MeDeCom_RProjSplxBox', PACKAGE = 'MeDeCom', Xinp, linp, uinp)
}

RQuadSimplex <- function(Ginp, Winp, Ainp, ot) {
    .Call('MeDeCom_RQuadSimplex', PACKAGE = 'MeDeCom', Ginp, Winp, Ainp, ot)
}

RQuadSimplexBox <- function(Ginp, Winp, Ainp, linp, uinp, ot) {
    .Call('MeDeCom_RQuadSimplexBox', PACKAGE = 'MeDeCom', Ginp, Winp, Ainp, linp, uinp, ot)
}

